<?php
require_once "animal.php";
require_once "perro.php";
require_once "gato.php";
$animal = new Animal();
$animal->asignarNombres("Calaberin");
$animal->asignarFechaNacimiento("05-06-2022");
$animal->asignarClasificacion("Pequeño");
$animal->asignarColor("Blanco");
$animal->mostrarTodo();
$animal->caminar();
$animal->saltar();
$animal->comer();
echo "<hr>";
$perro = new Perro();
$perro->asignarNombres("Cachuchin");
$perro->asignarFechaNacimiento("01-01-2019");
$perro->asignarClasificacion("Grande");
$perro->asignarColor("Negrito");
$perro->asignarApodo("Cachulin123");
$perro->mostrarTodo();
$perro->caminar();
$perro->saltar();
$perro->comer();
$perro->aullar();
$perro->morder();
echo "<hr>";
$gata = new Gato();
$gata->asignarNombres("Carlita");
$gata->asignarFechaNacimiento("25-25-2020");
$gata->asignarClasificacion("Mediano");
$gata->asignarColor("Plomo");
$gata->asignarApodo("Roxi123");
$gata->mostrarTodo();
$gata->caminar();
$gata->saltar();
$gata->comer();
$gata->arañar();
echo "<hr>";
